# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm (for any package.json files)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      # Group all npm development dependencies updates into a single PR
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5

  # Note: Dependabot doesn't yet support Deno/JSR dependencies directly
  # When it does, we would add:
  # - package-ecosystem: "deno"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
