/**
 * Version information for Nagare (流れ)
 * Generated by Nagare on 2025-07-01T04:40:37.605Z
 */

export const VERSION = "1.7.1";

export const BUILD_INFO = {
  buildDate: "2025-07-01T04:40:37.605Z",
  gitCommit: "30ee84c",
  buildEnvironment: "production",
  versionComponents: {
    major: 1,
    minor: 7,
    patch: 1,
    prerelease: null,
  },
} as const;

export const APP_INFO = {
  name: "Nagare (流れ)",
  description: "Deno Release Management Library",
  repository: "https://github.com/RickCogley/nagare",
  author: "Rick Cogley",
  homepage: "https://jsr.io/@rick/nagare",
  license: "MIT",
} as const;
export const APP_METADATA = {} as const;
export const RELEASE_NOTES = {
  "version": "1.7.1",
  "date": "2025-07-01",
  "added": [],
  "changed": [],
  "deprecated": [],
  "removed": [],
  "fixed": [
    "use safe filter for numeric version components in templates (30ee84c)",
    "correct syntax error in version.ts after v1.7.0 release (92389a4)"
  ],
  "security": []
} as const;
