/**
 * Version information for Nagare (流れ)
 * Generated by Nagare on 2025-06-30T20:17:06.293Z
 */

export const VERSION = "1.5.2";

export const BUILD_INFO = {
  buildDate: "2025-06-30T20:17:06.293Z",
  gitCommit: "047df1e",
  buildEnvironment: "production",
  versionComponents: {
    major: 1,
    minor: 5,
    patch: 2,
    prerelease: null
  }
} as const;

export const APP_INFO = {
  name: "Nagare (流れ)",
  description: "Deno Release Management Library",
  repository: "https://github.com/RickCogley/nagare",
  author: "Rick Cogley",
  homepage: "https://jsr.io/@rick/nagare",
  license: "MIT",
} as const;
export const APP_METADATA = {} as const;
export const RELEASE_NOTES = {} as const;
